### ISSUE TITLE
Links disappear after hovering.

### ISSUE THREAD

**Issue by aFrogThatExists** [the-coop/coop-website#77]
**Steps to reproduce**
- Hover over the "Play" button then stop hovering over it
- The icon and button disappears for a second.
![image](https://github.com/the-coop/coop-website/assets/54812998/e891ad89-af1b-4e75-a6ef-5a74a5fde73d)

**Comment by lmf-git** [comment]
I think I just fixed this, ty!

**Comment by lmf-git** [comment]
Okay it's a bit harder than I thought, it has to apply to the dropdowns too
