### ISSUE TITLE
Item Overview on hover

### ISSUE THREAD

**Issue by Simon5052** [the-coop/coop-website#78]
when hovering on item changing the font color to white will be better for visibility

**Comment by lmf-git** [comment]
<img width="716" alt="image" src="https://github.com/the-coop/coop-website/assets/67340984/41f0399b-aa33-4c37-90aa-2428ebc45e4d">

Good catch, the heights should be standardised too and maybe bold font?

**Comment by lmf-git** [comment]
<img width="1431" alt="image" src="https://github.com/the-coop/coop-website/assets/67340984/01c97073-38bd-43d5-bb14-166bc45e40e0">

**Comment by Simon5052** [comment]
I think this is a different issue. The one I resolved was more on the User leaderboard On Oct 15, 2023, at 4:17 AM, LMF ***@***.***> wrote:﻿
